pull_request_title: '[ci skip] New Crowdin translations'
commit_message: '[ci skip]'
files:
  - source: /public/locales/en-US/*.json
    translation: /public/locales/%locale%/%original_file_name%
  - source: /src/pages/docs/en-US/*.mdx
    translation: /src/pages/docs/%locale%/%original_file_name%
